/**
 * Pulse Food AI — Demo Nutrition Database
 *
 * A curated set of approximate nutrition records for common Indian and
 * international foods. All values are clearly labeled as estimates.
 *
 * Sources used as reference: USDA FoodData Central, NIN India Nutritive Value
 * of Indian Foods (ICMR), standard nutrition references.
 *
 * IMPORTANT: These are approximate estimates for demo/development use.
 * Real production deployments should connect to a licensed nutrition database.
 * Never present these values as laboratory-measured data.
 */

import { NutritionRecord, PortionConversion } from "./types";

// Common Indian household portion conversions (approximate)
const KATORI: PortionConversion = { unit: "katori", grams: 150 };  // ~150 ml bowl
const SMALL_KATORI: PortionConversion = { unit: "small katori", grams: 100 };
const ROTI: PortionConversion = { unit: "roti", grams: 30 };
const PARATHA: PortionConversion = { unit: "paratha", grams: 60 };
const IDLI: PortionConversion = { unit: "idli", grams: 45 };
const DOSA: PortionConversion = { unit: "dosa", grams: 90 };
const CUP: PortionConversion = { unit: "cup", grams: 240 };
const HALF_CUP: PortionConversion = { unit: "half cup", grams: 120 };
const TBSP: PortionConversion = { unit: "tablespoon", grams: 15 };
const TSP: PortionConversion = { unit: "teaspoon", grams: 5 };
const PIECE: PortionConversion = { unit: "piece", grams: 100 };
const SLICE: PortionConversion = { unit: "slice", grams: 30 };
const MEDIUM_PIECE: PortionConversion = { unit: "medium piece", grams: 150 };

const EST_NOTE =
  "⚠️ Approximate demo estimate. Recipe, preparation method, and exact ingredients significantly affect actual nutrition values. Not a substitute for laboratory-measured data.";

export const DEMO_NUTRITION_DB: NutritionRecord[] = [
  // ─── Cereals & Grains ─────────────────────────────────────────────────────
  {
    id: "demo-roti",
    provider: "demo",
    externalFoodId: "demo-roti",
    canonicalName: "Roti (Whole Wheat Chapati)",
    canonicalNameHi: "रोटी / चपाती",
    alternativeNames: ["chapati", "chapatti", "phulka", "wheat roti"],
    servingDescription: "1 medium roti (~30g)",
    defaultServingMass: 30,
    nutrients: { calories: 297, carbs: 57, protein: 11, fat: 3.7, fiber: 10.7 },
    portionConversions: [ROTI, { unit: "medium roti", grams: 30 }, { unit: "large roti", grams: 45 }],
    sourceReference: "NIN India, ICMR — Nutritive Value of Indian Foods (reference)",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-rice-cooked",
    provider: "demo",
    externalFoodId: "demo-rice-cooked",
    canonicalName: "Cooked White Rice",
    canonicalNameHi: "पके हुए चावल",
    alternativeNames: ["steamed rice", "boiled rice", "chawal", "plain rice", "rice"],
    servingDescription: "1 katori cooked rice (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 130, carbs: 28.2, protein: 2.7, fat: 0.3, fiber: 0.4 },
    portionConversions: [KATORI, SMALL_KATORI, CUP, HALF_CUP],
    sourceReference: "USDA FoodData Central FDC ID 168880 (reference)",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-paratha",
    provider: "demo",
    externalFoodId: "demo-paratha",
    canonicalName: "Plain Paratha",
    canonicalNameHi: "परांठा",
    alternativeNames: ["parantha", "plain paratha", "layered flatbread"],
    servingDescription: "1 medium paratha (~60g)",
    defaultServingMass: 60,
    nutrients: { calories: 328, carbs: 54, protein: 8, fat: 9.5, fiber: 5 },
    portionConversions: [PARATHA, { unit: "large paratha", grams: 90 }],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-poha",
    provider: "demo",
    externalFoodId: "demo-poha",
    canonicalName: "Poha (Flattened Rice, Cooked)",
    canonicalNameHi: "पोहा",
    alternativeNames: ["flattened rice", "beaten rice", "aval"],
    servingDescription: "1 katori cooked poha (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 180, carbs: 36, protein: 3.5, fat: 3, fiber: 1.5 },
    portionConversions: [KATORI, SMALL_KATORI],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-upma",
    provider: "demo",
    externalFoodId: "demo-upma",
    canonicalName: "Upma (Semolina, Cooked)",
    canonicalNameHi: "उपमा",
    alternativeNames: ["rava upma", "sooji upma", "semolina porridge"],
    servingDescription: "1 katori cooked upma (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 155, carbs: 26, protein: 4, fat: 4, fiber: 1.5 },
    portionConversions: [KATORI, SMALL_KATORI],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-idli",
    provider: "demo",
    externalFoodId: "demo-idli",
    canonicalName: "Idli (Steamed Rice Cake)",
    canonicalNameHi: "इडली",
    alternativeNames: ["idly", "steamed rice cake"],
    servingDescription: "1 medium idli (~45g)",
    defaultServingMass: 45,
    nutrients: { calories: 58, carbs: 11.6, protein: 2, fat: 0.4, fiber: 0.5 },
    portionConversions: [IDLI, { unit: "large idli", grams: 60 }],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-dosa",
    provider: "demo",
    externalFoodId: "demo-dosa",
    canonicalName: "Plain Dosa",
    canonicalNameHi: "डोसा",
    alternativeNames: ["dosai", "thin rice crepe", "crispy dosa"],
    servingDescription: "1 medium plain dosa (~90g)",
    defaultServingMass: 90,
    nutrients: { calories: 133, carbs: 27, protein: 3, fat: 1.5, fiber: 1 },
    portionConversions: [DOSA, { unit: "large dosa", grams: 130 }],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  // ─── Legumes & Pulses ─────────────────────────────────────────────────────
  {
    id: "demo-dal-cooked",
    provider: "demo",
    externalFoodId: "demo-dal-cooked",
    canonicalName: "Dal (Cooked Lentil Soup)",
    canonicalNameHi: "दाल",
    alternativeNames: ["lentil soup", "toor dal", "moong dal", "masoor dal", "arhar dal", "split pea soup"],
    servingDescription: "1 katori cooked dal (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 88, carbs: 14, protein: 6, fat: 1.5, fiber: 4 },
    portionConversions: [KATORI, SMALL_KATORI],
    sourceReference: "NIN India reference estimate. Note: Varies by dal type and preparation.",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE + " Dal nutrition varies significantly by type (toor, moong, masoor) and preparation.",
  },
  {
    id: "demo-rajma",
    provider: "demo",
    externalFoodId: "demo-rajma",
    canonicalName: "Rajma (Kidney Bean Curry)",
    canonicalNameHi: "राजमा",
    alternativeNames: ["kidney bean curry", "red bean curry"],
    servingDescription: "1 katori rajma curry (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 142, carbs: 21, protein: 8, fat: 3, fiber: 7 },
    portionConversions: [KATORI, SMALL_KATORI],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-chole",
    provider: "demo",
    externalFoodId: "demo-chole",
    canonicalName: "Chole (Chickpea Curry)",
    canonicalNameHi: "छोले / चने",
    alternativeNames: ["chana masala", "chickpea masala", "garbanzo curry"],
    servingDescription: "1 katori chole (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 160, carbs: 22, protein: 8.5, fat: 4, fiber: 6.5 },
    portionConversions: [KATORI, SMALL_KATORI],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-sambar",
    provider: "demo",
    externalFoodId: "demo-sambar",
    canonicalName: "Sambar",
    canonicalNameHi: "सांभर",
    alternativeNames: ["lentil vegetable stew", "south indian sambar"],
    servingDescription: "1 katori sambar (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 65, carbs: 9, protein: 4, fat: 1.5, fiber: 3 },
    portionConversions: [KATORI, SMALL_KATORI],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  // ─── Vegetables ───────────────────────────────────────────────────────────
  {
    id: "demo-mixed-veg-curry",
    provider: "demo",
    externalFoodId: "demo-mixed-veg-curry",
    canonicalName: "Mixed Vegetable Curry",
    canonicalNameHi: "मिक्स सब्जी",
    alternativeNames: ["sabzi", "vegetable sabzi", "mixed sabji", "mix vegetable"],
    servingDescription: "1 katori mixed vegetable curry (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 90, carbs: 12, protein: 3, fat: 3, fiber: 3.5 },
    portionConversions: [KATORI, SMALL_KATORI],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE + " Highly variable depending on oil used and vegetables included.",
  },
  {
    id: "demo-paneer",
    provider: "demo",
    externalFoodId: "demo-paneer",
    canonicalName: "Paneer Curry",
    canonicalNameHi: "पनीर",
    alternativeNames: ["cottage cheese curry", "paneer masala", "paneer sabzi", "paneer bhurji"],
    servingDescription: "1 katori paneer curry (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 240, carbs: 7, protein: 14, fat: 17, fiber: 1 },
    portionConversions: [KATORI, SMALL_KATORI, { unit: "piece", grams: 30 }],
    sourceReference: "NIN India reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  // ─── Dairy ───────────────────────────────────────────────────────────────
  {
    id: "demo-curd",
    provider: "demo",
    externalFoodId: "demo-curd",
    canonicalName: "Curd / Yogurt (Plain, Full Fat)",
    canonicalNameHi: "दही",
    alternativeNames: ["dahi", "plain yogurt", "set curd", "lassi base"],
    servingDescription: "1 katori curd (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 61, carbs: 4.7, protein: 3.5, fat: 3.3, fiber: 0 },
    portionConversions: [KATORI, SMALL_KATORI, CUP],
    sourceReference: "USDA FoodData Central reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  // ─── Snacks ──────────────────────────────────────────────────────────────
  {
    id: "demo-banana",
    provider: "demo",
    externalFoodId: "demo-banana",
    canonicalName: "Banana",
    canonicalNameHi: "केला",
    alternativeNames: ["kela", "ripe banana"],
    servingDescription: "1 medium banana (~120g edible portion)",
    defaultServingMass: 120,
    nutrients: { calories: 89, carbs: 23, protein: 1.1, fat: 0.3, fiber: 2.6 },
    portionConversions: [PIECE, { unit: "medium banana", grams: 120 }, { unit: "small banana", grams: 80 }],
    sourceReference: "USDA FoodData Central FDC ID 1105314 (reference)",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-apple",
    provider: "demo",
    externalFoodId: "demo-apple",
    canonicalName: "Apple",
    canonicalNameHi: "सेब",
    alternativeNames: ["seb", "red apple", "green apple"],
    servingDescription: "1 medium apple (~150g edible portion)",
    defaultServingMass: 150,
    nutrients: { calories: 52, carbs: 14, protein: 0.3, fat: 0.2, fiber: 2.4 },
    portionConversions: [PIECE, MEDIUM_PIECE, { unit: "medium apple", grams: 150 }],
    sourceReference: "USDA FoodData Central reference",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-egg",
    provider: "demo",
    externalFoodId: "demo-egg",
    canonicalName: "Egg (Boiled / Poached)",
    canonicalNameHi: "उबला अंडा",
    alternativeNames: ["anda", "hard boiled egg", "poached egg", "boiled egg"],
    servingDescription: "1 medium egg (~50g)",
    defaultServingMass: 50,
    nutrients: { calories: 155, carbs: 1.1, protein: 13, fat: 11, fiber: 0 },
    portionConversions: [{ unit: "egg", grams: 50 }, PIECE],
    sourceReference: "USDA FoodData Central reference",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE,
  },
  {
    id: "demo-salad",
    provider: "demo",
    externalFoodId: "demo-salad",
    canonicalName: "Green Salad (Mixed Leaves, Plain)",
    canonicalNameHi: "सलाद",
    alternativeNames: ["salad", "green salad", "mixed salad", "tossed salad"],
    servingDescription: "1 bowl salad (~150g)",
    defaultServingMass: 150,
    nutrients: { calories: 20, carbs: 3, protein: 1.5, fat: 0.3, fiber: 2 },
    portionConversions: [KATORI, { unit: "bowl", grams: 150 }],
    sourceReference: "USDA FoodData Central reference estimate",
    dataVersion: "demo-v1",
    isVerified: false,
    estimationNotes: EST_NOTE + " Dressings and toppings can significantly increase calorie content.",
  },
];

/** Quick index by canonical name (lower-cased) for fast lookup */
export const DEMO_FOOD_INDEX = new Map<string, NutritionRecord>(
  DEMO_NUTRITION_DB.flatMap((food) => [
    [food.canonicalName.toLowerCase(), food],
    ...food.alternativeNames.map((alias) => [alias.toLowerCase(), food] as [string, NutritionRecord]),
  ])
);
